Flownative:
  DoubleOptIn:
    presets:
      # the default preset is used if no other preset is requested
      'default':
        # the length of the generated token, in bytes, before hex encoding
        tokenLength: 32
        # how long a token should be valid after generation, in seconds
        lifetime: 86400
        # configuration for building an activation link for a token
        activation:
          # if uri is given as a string, it is used as given.
          # the placeholder -tokenhash- will be replaced with the token hash
          # uri: 'http://acme.com/activate/-tokenhash-'

          # if uri is a hash it is used as UriBuilder input (like in Routes.yaml)
          # the placeholder -tokenhash- will be replaced with the token hash in the built uri
          uri:
            '@package': ~
            '@subpackage': ~
            '@controller': ~
            '@format': ~
            '@action': ~
            arguments: ~
        mail:
          # name and email address to use for activation mails
          from:
            name: ~
            address: ~
          # subject to use for activation mails
          subject: 'Double Opt-In Activation Needed'
          # the message for the activation mail must contain a plain text part. an html part is optional
          # the settings must point to a Fluid template file. placeholders available in the templates when
          # being rendered: activationLink, recipientAddress, meta
          message:
            plaintext: 'resource://Flownative.DoubleOptIn/Private/Templates/ActivationMail.txt'
            html: ~
